# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\workspace\application\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 779)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(850, 750))
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/app.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.result_Layout = QtWidgets.QVBoxLayout()
        self.result_Layout.setObjectName("result_Layout")
        self.rs_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rs_label.sizePolicy().hasHeightForWidth())
        self.rs_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rs_label.setFont(font)
        self.rs_label.setAcceptDrops(True)
        self.rs_label.setObjectName("rs_label")
        self.result_Layout.addWidget(self.rs_label)
        spacerItem = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.result_Layout.addItem(spacerItem)
        self.gridLayout.addLayout(self.result_Layout, 0, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 1, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 1, 0, 1, 3)
        self.LeftBox = QtWidgets.QVBoxLayout()
        self.LeftBox.setContentsMargins(0, -1, -1, -1)
        self.LeftBox.setObjectName("LeftBox")
        self.cm_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cm_label.sizePolicy().hasHeightForWidth())
        self.cm_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cm_label.setFont(font)
        self.cm_label.setObjectName("cm_label")
        self.LeftBox.addWidget(self.cm_label)
        self.model_Layout = QtWidgets.QHBoxLayout()
        self.model_Layout.setObjectName("model_Layout")
        self.list_Box = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_Box.sizePolicy().hasHeightForWidth())
        self.list_Box.setSizePolicy(sizePolicy)
        self.list_Box.setMinimumSize(QtCore.QSize(220, 0))
        self.list_Box.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.list_Box.setFont(font)
        self.list_Box.setObjectName("list_Box")
        self.model_Layout.addWidget(self.list_Box)
        self.loadnet_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadnet_button.sizePolicy().hasHeightForWidth())
        self.loadnet_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.loadnet_button.setFont(font)
        self.loadnet_button.setObjectName("loadnet_button")
        self.model_Layout.addWidget(self.loadnet_button)
        self.LeftBox.addLayout(self.model_Layout)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.LeftBox.addWidget(self.line_2)
        self.cp_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cp_label.sizePolicy().hasHeightForWidth())
        self.cp_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cp_label.setFont(font)
        self.cp_label.setObjectName("cp_label")
        self.LeftBox.addWidget(self.cp_label)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.size_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.size_label.setFont(font)
        self.size_label.setObjectName("size_label")
        self.horizontalLayout_4.addWidget(self.size_label)
        self.img_size_box = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.img_size_box.setFont(font)
        self.img_size_box.setMinimum(1)
        self.img_size_box.setMaximum(1000000000)
        self.img_size_box.setProperty("value", 32)
        self.img_size_box.setObjectName("img_size_box")
        self.horizontalLayout_4.addWidget(self.img_size_box)
        self.LeftBox.addLayout(self.horizontalLayout_4)
        self.pic_Layout = QtWidgets.QHBoxLayout()
        self.pic_Layout.setContentsMargins(0, -1, 0, -1)
        self.pic_Layout.setSpacing(6)
        self.pic_Layout.setObjectName("pic_Layout")
        self.img_View = QtWidgets.QLabel(self.centralwidget)
        self.img_View.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_View.sizePolicy().hasHeightForWidth())
        self.img_View.setSizePolicy(sizePolicy)
        self.img_View.setMinimumSize(QtCore.QSize(120, 120))
        self.img_View.setMaximumSize(QtCore.QSize(120, 120))
        self.img_View.setAcceptDrops(False)
        self.img_View.setAutoFillBackground(False)
        self.img_View.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid;\n"
"border-color: rgb(95, 95, 95);")
        self.img_View.setText("")
        self.img_View.setScaledContents(True)
        self.img_View.setAlignment(QtCore.Qt.AlignCenter)
        self.img_View.setObjectName("img_View")
        self.pic_Layout.addWidget(self.img_View)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.is_Img = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.is_Img.sizePolicy().hasHeightForWidth())
        self.is_Img.setSizePolicy(sizePolicy)
        self.is_Img.setMinimumSize(QtCore.QSize(100, 0))
        self.is_Img.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.is_Img.setFont(font)
        self.is_Img.setStyleSheet("")
        self.is_Img.setObjectName("is_Img")
        self.verticalLayout.addWidget(self.is_Img)
        self.is_Square = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.is_Square.sizePolicy().hasHeightForWidth())
        self.is_Square.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.is_Square.setFont(font)
        self.is_Square.setObjectName("is_Square")
        self.verticalLayout.addWidget(self.is_Square)
        self.img_Size = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_Size.sizePolicy().hasHeightForWidth())
        self.img_Size.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.img_Size.setFont(font)
        self.img_Size.setStyleSheet("")
        self.img_Size.setObjectName("img_Size")
        self.verticalLayout.addWidget(self.img_Size)
        self.loadpic_Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadpic_Button.sizePolicy().hasHeightForWidth())
        self.loadpic_Button.setSizePolicy(sizePolicy)
        self.loadpic_Button.setMinimumSize(QtCore.QSize(220, 0))
        self.loadpic_Button.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.loadpic_Button.setFont(font)
        self.loadpic_Button.setObjectName("loadpic_Button")
        self.verticalLayout.addWidget(self.loadpic_Button)
        self.pic_Layout.addLayout(self.verticalLayout)
        self.LeftBox.addLayout(self.pic_Layout)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.LeftBox.addWidget(self.line_3)
        self.predict_button = QtWidgets.QPushButton(self.centralwidget)
        self.predict_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.predict_button.sizePolicy().hasHeightForWidth())
        self.predict_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.predict_button.setFont(font)
        self.predict_button.setObjectName("predict_button")
        self.LeftBox.addWidget(self.predict_button)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.reset_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        self.reset_button.setFont(font)
        self.reset_button.setStyleSheet("")
        self.reset_button.setObjectName("reset_button")
        self.horizontalLayout.addWidget(self.reset_button)
        self.test_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.test_button.setFont(font)
        self.test_button.setObjectName("test_button")
        self.horizontalLayout.addWidget(self.test_button)
        self.LeftBox.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.guide_Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.guide_Button.sizePolicy().hasHeightForWidth())
        self.guide_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.guide_Button.setFont(font)
        self.guide_Button.setObjectName("guide_Button")
        self.horizontalLayout_2.addWidget(self.guide_Button)
        self.about_Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.about_Button.sizePolicy().hasHeightForWidth())
        self.about_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.about_Button.setFont(font)
        self.about_Button.setObjectName("about_Button")
        self.horizontalLayout_2.addWidget(self.about_Button)
        self.LeftBox.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.LeftBox.addItem(spacerItem1)
        self.gridLayout.addLayout(self.LeftBox, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.log_Label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log_Label.sizePolicy().hasHeightForWidth())
        self.log_Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.log_Label.setFont(font)
        self.log_Label.setObjectName("log_Label")
        self.verticalLayout_3.addWidget(self.log_Label)
        self.log_Box = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log_Box.sizePolicy().hasHeightForWidth())
        self.log_Box.setSizePolicy(sizePolicy)
        self.log_Box.setMinimumSize(QtCore.QSize(0, 300))
        self.log_Box.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.log_Box.setFont(font)
        self.log_Box.setObjectName("log_Box")
        self.verticalLayout_3.addWidget(self.log_Box)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bar_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.bar_label.setFont(font)
        self.bar_label.setObjectName("bar_label")
        self.horizontalLayout_3.addWidget(self.bar_label)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_3.addWidget(self.progressBar)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_3, 2, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CIFAR-10 PREDICT"))
        self.rs_label.setText(_translate("MainWindow", "Result"))
        self.cm_label.setText(_translate("MainWindow", "Choose Model"))
        self.loadnet_button.setText(_translate("MainWindow", "LOAD"))
        self.cp_label.setText(_translate("MainWindow", "Choose Img"))
        self.size_label.setText(_translate("MainWindow", "图像大小"))
        self.is_Img.setText(_translate("MainWindow", "<strong style=\"white-space: pre; font-family:Consolas\">Is Img:</strong>"))
        self.is_Square.setText(_translate("MainWindow", "<strong style=\"white-space: pre; font-family:Consolas\">Is Square:</strong>"))
        self.img_Size.setText(_translate("MainWindow", "<strong style=\"white-space: pre; font-family:Consolas\">Img Size: </strong>"))
        self.loadpic_Button.setText(_translate("MainWindow", "Load Image"))
        self.predict_button.setText(_translate("MainWindow", "Predict"))
        self.reset_button.setText(_translate("MainWindow", "Reset"))
        self.test_button.setText(_translate("MainWindow", "Test Acc"))
        self.guide_Button.setText(_translate("MainWindow", "Guide"))
        self.about_Button.setText(_translate("MainWindow", "About"))
        self.log_Label.setText(_translate("MainWindow", "Logs"))
        self.bar_label.setText(_translate("MainWindow", "Progress: "))

import res_rc
