# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Project\training_GUI\main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(899, 707)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/app.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("更纱黑体 UI SC")
        font.setPointSize(10)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setVerticalSpacing(1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(6, 3, 6, 3)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.main_pgbar = QtWidgets.QProgressBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_pgbar.sizePolicy().hasHeightForWidth())
        self.main_pgbar.setSizePolicy(sizePolicy)
        self.main_pgbar.setMaximumSize(QtCore.QSize(16777215, 15))
        self.main_pgbar.setProperty("value", 24)
        self.main_pgbar.setTextVisible(False)
        self.main_pgbar.setObjectName("main_pgbar")
        self.horizontalLayout_3.addWidget(self.main_pgbar)
        self.label_main = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_main.sizePolicy().hasHeightForWidth())
        self.label_main.setSizePolicy(sizePolicy)
        self.label_main.setMinimumSize(QtCore.QSize(60, 0))
        self.label_main.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_main.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_main.setObjectName("label_main")
        self.horizontalLayout_3.addWidget(self.label_main)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sub_pgbar = QtWidgets.QProgressBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sub_pgbar.sizePolicy().hasHeightForWidth())
        self.sub_pgbar.setSizePolicy(sizePolicy)
        self.sub_pgbar.setMaximumSize(QtCore.QSize(16777215, 15))
        self.sub_pgbar.setProperty("value", 24)
        self.sub_pgbar.setTextVisible(False)
        self.sub_pgbar.setObjectName("sub_pgbar")
        self.horizontalLayout.addWidget(self.sub_pgbar)
        self.label_sub = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sub.sizePolicy().hasHeightForWidth())
        self.label_sub.setSizePolicy(sizePolicy)
        self.label_sub.setMinimumSize(QtCore.QSize(60, 0))
        self.label_sub.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_sub.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_sub.setObjectName("label_sub")
        self.horizontalLayout.addWidget(self.label_sub)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_5.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.control_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.control_tab.sizePolicy().hasHeightForWidth())
        self.control_tab.setSizePolicy(sizePolicy)
        self.control_tab.setObjectName("control_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.control_tab)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.lr_group = QtWidgets.QGroupBox(self.control_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lr_group.sizePolicy().hasHeightForWidth())
        self.lr_group.setSizePolicy(sizePolicy)
        self.lr_group.setObjectName("lr_group")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.lr_group)
        self.gridLayout_6.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_6.setHorizontalSpacing(6)
        self.gridLayout_6.setVerticalSpacing(4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.warmup_box = QtWidgets.QSpinBox(self.lr_group)
        self.warmup_box.setProperty("value", 5)
        self.warmup_box.setObjectName("warmup_box")
        self.gridLayout_6.addWidget(self.warmup_box, 4, 3, 1, 1)
        self.factor_decay_btn = QtWidgets.QRadioButton(self.lr_group)
        self.factor_decay_btn.setChecked(True)
        self.factor_decay_btn.setObjectName("factor_decay_btn")
        self.decay_btn_group = QtWidgets.QButtonGroup(MainWindow)
        self.decay_btn_group.setObjectName("decay_btn_group")
        self.decay_btn_group.addButton(self.factor_decay_btn)
        self.gridLayout_6.addWidget(self.factor_decay_btn, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.lr_group)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 3, 0, 2, 1)
        self.wd_box = QtWidgets.QLineEdit(self.lr_group)
        self.wd_box.setObjectName("wd_box")
        self.gridLayout_6.addWidget(self.wd_box, 0, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.lr_group)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 4, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.lr_group)
        self.label_22.setObjectName("label_22")
        self.gridLayout_6.addWidget(self.label_22, 0, 2, 1, 1)
        self.opt_box = QtWidgets.QComboBox(self.lr_group)
        self.opt_box.setObjectName("opt_box")
        self.opt_box.addItem("")
        self.gridLayout_6.addWidget(self.opt_box, 1, 1, 1, 1)
        self.lr_box = QtWidgets.QLineEdit(self.lr_group)
        self.lr_box.setObjectName("lr_box")
        self.gridLayout_6.addWidget(self.lr_box, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.lr_group)
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 1, 0, 1, 1)
        self.opt_args_btn = QtWidgets.QPushButton(self.lr_group)
        self.opt_args_btn.setObjectName("opt_args_btn")
        self.gridLayout_6.addWidget(self.opt_args_btn, 1, 3, 1, 1)
        self.line = QtWidgets.QFrame(self.lr_group)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_6.addWidget(self.line, 2, 0, 1, 4)
        self.cosine_decay_btn = QtWidgets.QRadioButton(self.lr_group)
        self.cosine_decay_btn.setChecked(False)
        self.cosine_decay_btn.setObjectName("cosine_decay_btn")
        self.decay_btn_group.addButton(self.cosine_decay_btn)
        self.gridLayout_6.addWidget(self.cosine_decay_btn, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.lr_group)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.lr_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.factor_epoch_box = QtWidgets.QLineEdit(self.lr_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.factor_epoch_box.sizePolicy().hasHeightForWidth())
        self.factor_epoch_box.setSizePolicy(sizePolicy)
        self.factor_epoch_box.setMaximumSize(QtCore.QSize(50, 16777215))
        self.factor_epoch_box.setObjectName("factor_epoch_box")
        self.horizontalLayout_2.addWidget(self.factor_epoch_box)
        self.label_10 = QtWidgets.QLabel(self.lr_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.factor_pow_box = QtWidgets.QLineEdit(self.lr_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.factor_pow_box.sizePolicy().hasHeightForWidth())
        self.factor_pow_box.setSizePolicy(sizePolicy)
        self.factor_pow_box.setMaximumSize(QtCore.QSize(50, 16777215))
        self.factor_pow_box.setObjectName("factor_pow_box")
        self.horizontalLayout_2.addWidget(self.factor_pow_box)
        self.gridLayout_6.addLayout(self.horizontalLayout_2, 3, 2, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.lr_group)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 1, 2, 1, 1)
        self.gridLayout_6.setColumnStretch(0, 1)
        self.gridLayout.addWidget(self.lr_group, 2, 1, 1, 2)
        self.train_group = QtWidgets.QGroupBox(self.control_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.train_group.sizePolicy().hasHeightForWidth())
        self.train_group.setSizePolicy(sizePolicy)
        self.train_group.setObjectName("train_group")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.train_group)
        self.gridLayout_8.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_8.setHorizontalSpacing(6)
        self.gridLayout_8.setVerticalSpacing(4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.epoch_box = QtWidgets.QLineEdit(self.train_group)
        self.epoch_box.setObjectName("epoch_box")
        self.gridLayout_8.addWidget(self.epoch_box, 0, 1, 1, 1)
        self.gpu_num_box = QtWidgets.QSpinBox(self.train_group)
        self.gpu_num_box.setObjectName("gpu_num_box")
        self.gridLayout_8.addWidget(self.gpu_num_box, 3, 1, 1, 1)
        self.amp_btn = QtWidgets.QCheckBox(self.train_group)
        self.amp_btn.setObjectName("amp_btn")
        self.gridLayout_8.addWidget(self.amp_btn, 3, 2, 1, 2)
        self.label_20 = QtWidgets.QLabel(self.train_group)
        self.label_20.setObjectName("label_20")
        self.gridLayout_8.addWidget(self.label_20, 0, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.train_group)
        self.label_21.setObjectName("label_21")
        self.gridLayout_8.addWidget(self.label_21, 3, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.train_group)
        self.label_18.setObjectName("label_18")
        self.gridLayout_8.addWidget(self.label_18, 0, 2, 1, 1)
        self.batchsize_box = QtWidgets.QLineEdit(self.train_group)
        self.batchsize_box.setObjectName("batchsize_box")
        self.gridLayout_8.addWidget(self.batchsize_box, 0, 3, 1, 1)
        self.load_param_btn = QtWidgets.QRadioButton(self.train_group)
        self.load_param_btn.setObjectName("load_param_btn")
        self.param_btn_group = QtWidgets.QButtonGroup(MainWindow)
        self.param_btn_group.setObjectName("param_btn_group")
        self.param_btn_group.addButton(self.load_param_btn)
        self.gridLayout_8.addWidget(self.load_param_btn, 2, 0, 1, 2)
        self.init_btn = QtWidgets.QRadioButton(self.train_group)
        self.init_btn.setChecked(True)
        self.init_btn.setObjectName("init_btn")
        self.param_btn_group.addButton(self.init_btn)
        self.gridLayout_8.addWidget(self.init_btn, 1, 0, 1, 2)
        self.param_file_btn = QtWidgets.QPushButton(self.train_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.param_file_btn.sizePolicy().hasHeightForWidth())
        self.param_file_btn.setSizePolicy(sizePolicy)
        self.param_file_btn.setObjectName("param_file_btn")
        self.gridLayout_8.addWidget(self.param_file_btn, 2, 2, 1, 2)
        self.init_box = QtWidgets.QComboBox(self.train_group)
        self.init_box.setObjectName("init_box")
        self.init_box.addItem("")
        self.gridLayout_8.addWidget(self.init_box, 1, 2, 1, 2)
        self.gridLayout_8.setColumnStretch(0, 1)
        self.gridLayout.addWidget(self.train_group, 2, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.net_group = QtWidgets.QGroupBox(self.control_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.net_group.sizePolicy().hasHeightForWidth())
        self.net_group.setSizePolicy(sizePolicy)
        self.net_group.setFlat(False)
        self.net_group.setCheckable(False)
        self.net_group.setObjectName("net_group")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.net_group)
        self.gridLayout_4.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_4.setHorizontalSpacing(6)
        self.gridLayout_4.setVerticalSpacing(4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.net_args_btn = QtWidgets.QPushButton(self.net_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.net_args_btn.sizePolicy().hasHeightForWidth())
        self.net_args_btn.setSizePolicy(sizePolicy)
        self.net_args_btn.setObjectName("net_args_btn")
        self.gridLayout_4.addWidget(self.net_args_btn, 2, 1, 1, 1)
        self.net_file_btn = QtWidgets.QPushButton(self.net_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.net_file_btn.sizePolicy().hasHeightForWidth())
        self.net_file_btn.setSizePolicy(sizePolicy)
        self.net_file_btn.setObjectName("net_file_btn")
        self.gridLayout_4.addWidget(self.net_file_btn, 0, 1, 1, 1)
        self.load_net_btn = QtWidgets.QPushButton(self.net_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_net_btn.sizePolicy().hasHeightForWidth())
        self.load_net_btn.setSizePolicy(sizePolicy)
        self.load_net_btn.setObjectName("load_net_btn")
        self.gridLayout_4.addWidget(self.load_net_btn, 5, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.net_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.net_name_box = QtWidgets.QLineEdit(self.net_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.net_name_box.sizePolicy().hasHeightForWidth())
        self.net_name_box.setSizePolicy(sizePolicy)
        self.net_name_box.setObjectName("net_name_box")
        self.gridLayout_4.addWidget(self.net_name_box, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.net_group)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.net_group)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.net_group)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 2, 0, 1, 1)
        self.net_class_box = QtWidgets.QLineEdit(self.net_group)
        self.net_class_box.setObjectName("net_class_box")
        self.gridLayout_4.addWidget(self.net_class_box, 1, 1, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 2)
        self.gridLayout.addWidget(self.net_group, 1, 1, 1, 2)
        self.save_group = QtWidgets.QGroupBox(self.control_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_group.sizePolicy().hasHeightForWidth())
        self.save_group.setSizePolicy(sizePolicy)
        self.save_group.setObjectName("save_group")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.save_group)
        self.gridLayout_12.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_12.setVerticalSpacing(4)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.tensorboard_btn = QtWidgets.QCheckBox(self.save_group)
        self.tensorboard_btn.setChecked(True)
        self.tensorboard_btn.setObjectName("tensorboard_btn")
        self.gridLayout_12.addWidget(self.tensorboard_btn, 0, 0, 1, 1)
        self.profiler_btn = QtWidgets.QCheckBox(self.save_group)
        self.profiler_btn.setChecked(True)
        self.profiler_btn.setObjectName("profiler_btn")
        self.gridLayout_12.addWidget(self.profiler_btn, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.save_group, 5, 3, 1, 1)
        self.dataset_group = QtWidgets.QGroupBox(self.control_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataset_group.sizePolicy().hasHeightForWidth())
        self.dataset_group.setSizePolicy(sizePolicy)
        self.dataset_group.setObjectName("dataset_group")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.dataset_group)
        self.gridLayout_7.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_7.setHorizontalSpacing(6)
        self.gridLayout_7.setVerticalSpacing(4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.cutout_btn = QtWidgets.QCheckBox(self.dataset_group)
        self.cutout_btn.setObjectName("cutout_btn")
        self.gridLayout_7.addWidget(self.cutout_btn, 3, 1, 1, 1)
        self.crop_pad_box = QtWidgets.QSpinBox(self.dataset_group)
        self.crop_pad_box.setProperty("value", 4)
        self.crop_pad_box.setObjectName("crop_pad_box")
        self.gridLayout_7.addWidget(self.crop_pad_box, 2, 3, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.dataset_group)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_7.addWidget(self.line_2, 1, 0, 1, 4)
        self.label_19 = QtWidgets.QLabel(self.dataset_group)
        self.label_19.setObjectName("label_19")
        self.gridLayout_7.addWidget(self.label_19, 5, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.dataset_group)
        self.label_16.setObjectName("label_16")
        self.gridLayout_7.addWidget(self.label_16, 2, 2, 1, 1)
        self.cutout_size_box = QtWidgets.QSpinBox(self.dataset_group)
        self.cutout_size_box.setProperty("value", 8)
        self.cutout_size_box.setObjectName("cutout_size_box")
        self.gridLayout_7.addWidget(self.cutout_size_box, 3, 3, 1, 1)
        self.mixup_alpha_box = QtWidgets.QLineEdit(self.dataset_group)
        self.mixup_alpha_box.setObjectName("mixup_alpha_box")
        self.gridLayout_7.addWidget(self.mixup_alpha_box, 5, 3, 1, 1)
        self.mixup_btn = QtWidgets.QCheckBox(self.dataset_group)
        self.mixup_btn.setObjectName("mixup_btn")
        self.gridLayout_7.addWidget(self.mixup_btn, 5, 1, 1, 1)
        self.worker_box = QtWidgets.QSpinBox(self.dataset_group)
        self.worker_box.setObjectName("worker_box")
        self.gridLayout_7.addWidget(self.worker_box, 0, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.dataset_group)
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 0, 2, 1, 1)
        self.flip_btn = QtWidgets.QCheckBox(self.dataset_group)
        self.flip_btn.setChecked(True)
        self.flip_btn.setObjectName("flip_btn")
        self.gridLayout_7.addWidget(self.flip_btn, 4, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.dataset_group)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.dataset_group)
        self.label_17.setObjectName("label_17")
        self.gridLayout_7.addWidget(self.label_17, 3, 2, 1, 1)
        self.img_size_box = QtWidgets.QSpinBox(self.dataset_group)
        self.img_size_box.setProperty("value", 32)
        self.img_size_box.setObjectName("img_size_box")
        self.gridLayout_7.addWidget(self.img_size_box, 0, 1, 1, 1)
        self.crop_btn = QtWidgets.QCheckBox(self.dataset_group)
        self.crop_btn.setChecked(True)
        self.crop_btn.setObjectName("crop_btn")
        self.gridLayout_7.addWidget(self.crop_btn, 2, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.dataset_group)
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 0, 0, 1, 1)
        self.erase_btn = QtWidgets.QCheckBox(self.dataset_group)
        self.erase_btn.setObjectName("erase_btn")
        self.gridLayout_7.addWidget(self.erase_btn, 4, 2, 1, 2)
        self.gridLayout.addWidget(self.dataset_group, 1, 3, 1, 1)
        self.dir_group = QtWidgets.QGroupBox(self.control_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dir_group.sizePolicy().hasHeightForWidth())
        self.dir_group.setSizePolicy(sizePolicy)
        self.dir_group.setObjectName("dir_group")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.dir_group)
        self.gridLayout_10.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.dir_edit_btn = QtWidgets.QPushButton(self.dir_group)
        self.dir_edit_btn.setObjectName("dir_edit_btn")
        self.gridLayout_10.addWidget(self.dir_edit_btn, 0, 1, 1, 1)
        self.workdir_box = QtWidgets.QLineEdit(self.dir_group)
        self.workdir_box.setEnabled(True)
        self.workdir_box.setReadOnly(True)
        self.workdir_box.setClearButtonEnabled(False)
        self.workdir_box.setObjectName("workdir_box")
        self.gridLayout_10.addWidget(self.workdir_box, 0, 0, 1, 1)
        self.gridLayout_10.setColumnStretch(0, 2)
        self.gridLayout.addWidget(self.dir_group, 5, 1, 1, 2)
        self.datadir_group = QtWidgets.QGroupBox(self.control_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datadir_group.sizePolicy().hasHeightForWidth())
        self.datadir_group.setSizePolicy(sizePolicy)
        self.datadir_group.setObjectName("datadir_group")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.datadir_group)
        self.gridLayout_11.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.datadir_edit_btn = QtWidgets.QPushButton(self.datadir_group)
        self.datadir_edit_btn.setObjectName("datadir_edit_btn")
        self.gridLayout_11.addWidget(self.datadir_edit_btn, 0, 1, 1, 1)
        self.datadir_box = QtWidgets.QLineEdit(self.datadir_group)
        self.datadir_box.setEnabled(True)
        self.datadir_box.setReadOnly(True)
        self.datadir_box.setClearButtonEnabled(False)
        self.datadir_box.setObjectName("datadir_box")
        self.gridLayout_11.addWidget(self.datadir_box, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.datadir_group, 6, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 10, 1, 1, 1)
        self.btn_layout = QtWidgets.QHBoxLayout()
        self.btn_layout.setContentsMargins(9, 6, 9, 6)
        self.btn_layout.setObjectName("btn_layout")
        self.start_btn = QtWidgets.QPushButton(self.control_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_btn.sizePolicy().hasHeightForWidth())
        self.start_btn.setSizePolicy(sizePolicy)
        self.start_btn.setObjectName("start_btn")
        self.btn_layout.addWidget(self.start_btn)
        self.pause_btn = QtWidgets.QPushButton(self.control_tab)
        self.pause_btn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pause_btn.sizePolicy().hasHeightForWidth())
        self.pause_btn.setSizePolicy(sizePolicy)
        self.pause_btn.setObjectName("pause_btn")
        self.btn_layout.addWidget(self.pause_btn)
        self.stop_btn = QtWidgets.QPushButton(self.control_tab)
        self.stop_btn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_btn.sizePolicy().hasHeightForWidth())
        self.stop_btn.setSizePolicy(sizePolicy)
        self.stop_btn.setObjectName("stop_btn")
        self.btn_layout.addWidget(self.stop_btn)
        self.gridLayout.addLayout(self.btn_layout, 6, 3, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(4, 2)
        self.tabWidget.addTab(self.control_tab, "")
        self.data_tab = QtWidgets.QWidget()
        self.data_tab.setObjectName("data_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.data_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.data_table = QtWidgets.QTableView(self.data_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_table.sizePolicy().hasHeightForWidth())
        self.data_table.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("更纱黑体 UI SC")
        font.setPointSize(10)
        self.data_table.setFont(font)
        self.data_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.data_table.setAutoScroll(False)
        self.data_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.data_table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.data_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.data_table.setObjectName("data_table")
        self.data_table.horizontalHeader().setCascadingSectionResizes(True)
        self.data_table.verticalHeader().setVisible(False)
        self.data_table.verticalHeader().setCascadingSectionResizes(True)
        self.gridLayout_2.addWidget(self.data_table, 0, 0, 1, 1)
        self.tabWidget.addTab(self.data_tab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.log_box = QtWidgets.QTextBrowser(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log_box.sizePolicy().hasHeightForWidth())
        self.log_box.setSizePolicy(sizePolicy)
        self.log_box.setObjectName("log_box")
        self.gridLayout_16.addWidget(self.log_box, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.about_tab = QtWidgets.QWidget()
        self.about_tab.setObjectName("about_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.about_tab)
        self.gridLayout_3.setContentsMargins(9, 6, 9, 6)
        self.gridLayout_3.setVerticalSpacing(3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_34 = QtWidgets.QLabel(self.about_tab)
        self.label_34.setWordWrap(True)
        self.label_34.setObjectName("label_34")
        self.gridLayout_3.addWidget(self.label_34, 11, 1, 1, 2)
        self.tableWidget = QtWidgets.QTableWidget(self.about_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.gridLayout_3.addWidget(self.tableWidget, 7, 5, 5, 1)
        self.label_31 = QtWidgets.QLabel(self.about_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout_3.addWidget(self.label_31, 8, 1, 1, 2)
        self.label_24 = QtWidgets.QLabel(self.about_tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 7, 4, 3, 1)
        self.label_28 = QtWidgets.QLabel(self.about_tab)
        self.label_28.setTextFormat(QtCore.Qt.RichText)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 6, 5, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 35, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem4, 12, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem5, 0, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.about_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 3, 1, 1, 5)
        self.label_33 = QtWidgets.QLabel(self.about_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.gridLayout_3.addWidget(self.label_33, 10, 1, 1, 2)
        self.label_23 = QtWidgets.QLabel(self.about_tab)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 2, 1, 1, 5)
        self.label_8 = QtWidgets.QLabel(self.about_tab)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 1, 1, 5)
        self.label_29 = QtWidgets.QLabel(self.about_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 5, 1, 1, 2)
        self.line_4 = QtWidgets.QFrame(self.about_tab)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.line_4, 5, 3, 7, 1)
        self.label_27 = QtWidgets.QLabel(self.about_tab)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 5, 5, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 0, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.about_tab)
        self.label_32.setTextFormat(QtCore.Qt.PlainText)
        self.label_32.setWordWrap(True)
        self.label_32.setObjectName("label_32")
        self.gridLayout_3.addWidget(self.label_32, 9, 1, 1, 2)
        self.line_3 = QtWidgets.QFrame(self.about_tab)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_3.addWidget(self.line_3, 4, 1, 1, 5)
        self.label_25 = QtWidgets.QLabel(self.about_tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 5, 4, 2, 1)
        self.label_30 = QtWidgets.QLabel(self.about_tab)
        self.label_30.setWordWrap(True)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 6, 1, 2, 2)
        spacerItem7 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 7, 6, 1, 1)
        self.tabWidget.addTab(self.about_tab, "")
        self.gridLayout_5.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.workdir_box, self.dir_edit_btn)
        MainWindow.setTabOrder(self.dir_edit_btn, self.datadir_box)
        MainWindow.setTabOrder(self.datadir_box, self.datadir_edit_btn)
        MainWindow.setTabOrder(self.datadir_edit_btn, self.net_file_btn)
        MainWindow.setTabOrder(self.net_file_btn, self.net_name_box)
        MainWindow.setTabOrder(self.net_name_box, self.load_net_btn)
        MainWindow.setTabOrder(self.load_net_btn, self.start_btn)
        MainWindow.setTabOrder(self.start_btn, self.pause_btn)
        MainWindow.setTabOrder(self.pause_btn, self.stop_btn)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GUI Training"))
        self.label_main.setText(_translate("MainWindow", "0.0%"))
        self.label_sub.setText(_translate("MainWindow", "0.0%"))
        self.lr_group.setTitle(_translate("MainWindow", "学习率与优化器"))
        self.factor_decay_btn.setText(_translate("MainWindow", "Factor"))
        self.label_7.setText(_translate("MainWindow", "衰减方法"))
        self.wd_box.setText(_translate("MainWindow", "0.0005"))
        self.label_12.setText(_translate("MainWindow", "预热Epoch"))
        self.label_22.setText(_translate("MainWindow", "权重衰减"))
        self.opt_box.setItemText(0, _translate("MainWindow", "SGD"))
        self.lr_box.setText(_translate("MainWindow", "0.1"))
        self.label_11.setText(_translate("MainWindow", "优化器"))
        self.opt_args_btn.setText(_translate("MainWindow", "编辑"))
        self.cosine_decay_btn.setText(_translate("MainWindow", "Cosine"))
        self.label_6.setText(_translate("MainWindow", "学习率"))
        self.label_9.setText(_translate("MainWindow", "每"))
        self.factor_epoch_box.setText(_translate("MainWindow", "20"))
        self.label_10.setText(_translate("MainWindow", "Epoch衰减"))
        self.factor_pow_box.setText(_translate("MainWindow", "0.2"))
        self.label_5.setText(_translate("MainWindow", "额外参数"))
        self.train_group.setTitle(_translate("MainWindow", "训练选项"))
        self.epoch_box.setText(_translate("MainWindow", "80"))
        self.amp_btn.setText(_translate("MainWindow", "AMP训练"))
        self.label_20.setText(_translate("MainWindow", "Epoch"))
        self.label_21.setText(_translate("MainWindow", "GPU"))
        self.label_18.setText(_translate("MainWindow", "Batch Size"))
        self.batchsize_box.setText(_translate("MainWindow", "128"))
        self.load_param_btn.setText(_translate("MainWindow", "读取参数"))
        self.init_btn.setText(_translate("MainWindow", "初始化方法"))
        self.param_file_btn.setText(_translate("MainWindow", "选择文件"))
        self.init_box.setItemText(0, _translate("MainWindow", "Uniform"))
        self.net_group.setTitle(_translate("MainWindow", "网络"))
        self.net_args_btn.setText(_translate("MainWindow", "编辑"))
        self.net_file_btn.setText(_translate("MainWindow", "选择文件"))
        self.load_net_btn.setText(_translate("MainWindow", "读取网络"))
        self.label.setText(_translate("MainWindow", "包含网络的Python文件"))
        self.net_name_box.setText(_translate("MainWindow", "Net"))
        self.label_4.setText(_translate("MainWindow", "显示名称"))
        self.label_2.setText(_translate("MainWindow", "网络函数或类名"))
        self.label_3.setText(_translate("MainWindow", "额外参数（字典）"))
        self.save_group.setTitle(_translate("MainWindow", "数据储存"))
        self.tensorboard_btn.setText(_translate("MainWindow", "Tensorboard"))
        self.profiler_btn.setText(_translate("MainWindow", "Profiler"))
        self.dataset_group.setTitle(_translate("MainWindow", "数据集设定"))
        self.cutout_btn.setText(_translate("MainWindow", "Cutout"))
        self.label_19.setText(_translate("MainWindow", "alpha"))
        self.label_16.setText(_translate("MainWindow", "pad"))
        self.mixup_alpha_box.setText(_translate("MainWindow", "1"))
        self.mixup_btn.setText(_translate("MainWindow", "Mixup"))
        self.label_15.setText(_translate("MainWindow", "多进程读取"))
        self.flip_btn.setText(_translate("MainWindow", "左右翻转"))
        self.label_13.setText(_translate("MainWindow", "数据增强"))
        self.label_17.setText(_translate("MainWindow", "大小"))
        self.crop_btn.setText(_translate("MainWindow", "RandomCrop"))
        self.label_14.setText(_translate("MainWindow", "图像大小"))
        self.erase_btn.setText(_translate("MainWindow", "随机擦除"))
        self.dir_group.setTitle(_translate("MainWindow", "工作路径"))
        self.dir_edit_btn.setText(_translate("MainWindow", "修改"))
        self.workdir_box.setText(_translate("MainWindow", "C:/"))
        self.datadir_group.setTitle(_translate("MainWindow", "CIFAR-10数据集储存路径"))
        self.datadir_edit_btn.setText(_translate("MainWindow", "修改"))
        self.datadir_box.setText(_translate("MainWindow", "C:/dataset/"))
        self.start_btn.setText(_translate("MainWindow", "开始训练"))
        self.pause_btn.setText(_translate("MainWindow", "暂停"))
        self.stop_btn.setText(_translate("MainWindow", "停止"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.control_tab), _translate("MainWindow", "控制台"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.data_tab), _translate("MainWindow", "训练数据"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Log"))
        self.label_34.setText(_translate("MainWindow", "CIFAR-10是一个更接近普适物体的彩色图像数据集。一共包含10 个类别的RGB 彩色图片：飞机、汽车、鸟类、猫、鹿、狗、蛙类、马、船和卡车。每个图片的尺寸为32 × 32 ，每个类别有6000个图像，数据集中一共有50000 张训练图片和10000 张测试图片"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Package"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "版本"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "PyQt5"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "5.14.1"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "mxnet-cu101"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "1.5.0"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "mxboard"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "0.1.0"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "gluoncv"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("MainWindow", "0.6.0"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "matplotlib"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("MainWindow", "2.2.2"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("MainWindow", "numpy"))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("MainWindow", "1.16.6"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_31.setText(_translate("MainWindow", "关于Qt"))
        self.label_24.setText(_translate("MainWindow", "所用的Python包"))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"www.github.com\"><span style=\" text-decoration: underline; color:#0000ff;\">Github</span></a></p></body></html>"))
        self.label_26.setText(_translate("MainWindow", "用于2020东北大学计算机科学与工程学院本科毕业设计——《基于CIFAR-10的神经网络模型研究与实现》"))
        self.label_33.setText(_translate("MainWindow", "关于CIFAR-10"))
        self.label_23.setText(_translate("MainWindow", "简易的CIFAR-10训练工具"))
        self.label_8.setText(_translate("MainWindow", "GUI训练工具"))
        self.label_29.setText(_translate("MainWindow", "关于MXNET"))
        self.label_27.setText(_translate("MainWindow", "通信1603班 刘延益"))
        self.label_32.setText(_translate("MainWindow", "PyQt 是一个用于创建GUI应用程序的跨平台的工具包，它将Python编程语言和Qt库 成功融合在一起。QT库目前是最强大的GUI库之一。"))
        self.label_25.setText(_translate("MainWindow", "开发者"))
        self.label_30.setText(_translate("MainWindow", "MXNet是一款灵活且高效的深度学习库。\n"
"MXNet的高层接口是Gluon，Gluon同时支持灵活的动态图和高效的静态图，既保留动态图的易用性，也具有静态图的高性能。"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.about_tab), _translate("MainWindow", "关于"))

import res_rc
